# Generated by Django 3.0.5 on 2020-06-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EskoolyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteinfo',
            name='addfee',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='instituteinfo',
            name='artfee',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='instituteinfo',
            name='booksfee',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='instituteinfo',
            name='fine',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='instituteinfo',
            name='others',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='instituteinfo',
            name='regfee',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='instituteinfo',
            name='transportfee',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='instituteinfo',
            name='uniformfee',
            field=models.CharField(default='', max_length=40),
        ),
    ]
