# Generated by Django 3.0.5 on 2020-06-18 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EskoolyApp', '0002_auto_20200618_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reg_no', models.IntegerField()),
                ('picture', models.FileField(upload_to='images/')),
                ('Admission_date', models.DateField()),
                ('discount', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('orphan_student', models.BooleanField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True)),
                ('caste', models.CharField(blank=True, max_length=30, null=True)),
                ('previous_school', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, choices=[('buddhism', 'Buddhism'), ('christianity', 'Christianity'), ('hinduism', 'Hinduism'), ('islam', 'Islam'), ('jainism', 'Jainism'), ('sikhism', 'Sikhism'), ('other', 'Other')], max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_children', models.IntegerField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=20, null=True)),
                ('father_education', models.CharField(blank=True, max_length=20, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('father_income', models.FloatField(blank=True, null=True)),
                ('father_mobile', models.IntegerField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_education', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_income', models.FloatField(blank=True, null=True)),
                ('mother_mobile', models.IntegerField(blank=True, null=True)),
                ('name_of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EskoolyApp.Classes')),
            ],
        ),
    ]
