# Generated by Django 3.0.5 on 2020-06-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EskoolyApp', '0003_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
